# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Db.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DbWindow(object):
    def setupUi(self, DbWindow):
        DbWindow.setObjectName("DbWindow")
        DbWindow.resize(800, 400)
        DbWindow.setMinimumSize(QtCore.QSize(600, 300))
        DbWindow.setStyleSheet("background-color: rgb(106, 104, 98);\n"
"\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(76, 72, 102);")
        self.centralwidget = QtWidgets.QWidget(DbWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Db_Elems_sArea = QtWidgets.QScrollArea(self.centralwidget)
        self.Db_Elems_sArea.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(178, 0, 242);\n"
"\n"
"")
        self.Db_Elems_sArea.setWidgetResizable(True)
        self.Db_Elems_sArea.setObjectName("Db_Elems_sArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 772, 264))
        self.scrollAreaWidgetContents.setStyleSheet("border: 0px;")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(0, 5, 0, 5)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Db_Elems_vLayout = QtWidgets.QVBoxLayout()
        self.Db_Elems_vLayout.setSpacing(5)
        self.Db_Elems_vLayout.setObjectName("Db_Elems_vLayout")
        self.gridLayout_2.addLayout(self.Db_Elems_vLayout, 0, 0, 1, 1)
        self.Db_Elems_sArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.Db_Elems_sArea, 0, 0, 1, 1)
        self.Db_Update_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Db_Update_btn.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Db_Update_btn.setFont(font)
        self.Db_Update_btn.setStyleSheet("background-color: rgb(52, 52, 52);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(157, 123, 71);\n"
"\n"
"border: 3px solid rgb(178, 0, 242);")
        self.Db_Update_btn.setObjectName("Db_Update_btn")
        self.gridLayout.addWidget(self.Db_Update_btn, 1, 0, 1, 1)
        DbWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DbWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        DbWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DbWindow)
        self.statusbar.setObjectName("statusbar")
        DbWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DbWindow)
        QtCore.QMetaObject.connectSlotsByName(DbWindow)

    def retranslateUi(self, DbWindow):
        _translate = QtCore.QCoreApplication.translate
        DbWindow.setWindowTitle(_translate("DbWindow", "MainWindow"))
        self.Db_Update_btn.setText(_translate("DbWindow", "Обновить"))
