# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Violet2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        MainWindow.setMinimumSize(QtCore.QSize(850, 590))
        MainWindow.setStyleSheet("background-color: rgb(106, 104, 98);\n"
"background-color: rgb(79, 80, 86);\n"
"background-color: rgb(76, 72, 102);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 10)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Save_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Save_btn.sizePolicy().hasHeightForWidth())
        self.Save_btn.setSizePolicy(sizePolicy)
        self.Save_btn.setMinimumSize(QtCore.QSize(120, 50))
        self.Save_btn.setMaximumSize(QtCore.QSize(150, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Save_btn.setFont(font)
        self.Save_btn.setStyleSheet("background-color: rgb(52, 52, 52);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(157, 123, 71);\n"
"\n"
"border: 3px solid rgb(0, 85, 255);\n"
"\n"
"border: 3px solid rgb(178, 0, 242);\n"
"\n"
"border-right: 0px;\n"
"border-top: 0px;")
        self.Save_btn.setObjectName("Save_btn")
        self.horizontalLayout.addWidget(self.Save_btn)
        self.Bd_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bd_btn.sizePolicy().hasHeightForWidth())
        self.Bd_btn.setSizePolicy(sizePolicy)
        self.Bd_btn.setMinimumSize(QtCore.QSize(120, 50))
        self.Bd_btn.setMaximumSize(QtCore.QSize(150, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Bd_btn.setFont(font)
        self.Bd_btn.setStyleSheet("background-color: rgb(52, 52, 52);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(157, 123, 71);\n"
"\n"
"border: 3px solid rgb(0, 85, 255);\n"
"\n"
"border: 3px solid rgb(178, 0, 242);\n"
"\n"
"border-right: 0px;\n"
"border-top: 0px;")
        self.Bd_btn.setObjectName("Bd_btn")
        self.horizontalLayout.addWidget(self.Bd_btn)
        self.Histogram_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Histogram_btn.sizePolicy().hasHeightForWidth())
        self.Histogram_btn.setSizePolicy(sizePolicy)
        self.Histogram_btn.setMinimumSize(QtCore.QSize(120, 50))
        self.Histogram_btn.setMaximumSize(QtCore.QSize(150, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Histogram_btn.setFont(font)
        self.Histogram_btn.setStyleSheet("background-color: rgb(52, 52, 52);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(157, 123, 71);\n"
"\n"
"border: 3px solid rgb(0, 85, 255);\n"
"\n"
"border: 3px solid rgb(178, 0, 242);\n"
"\n"
"border-right: 0px;\n"
"border-top: 0px;")
        self.Histogram_btn.setObjectName("Histogram_btn")
        self.horizontalLayout.addWidget(self.Histogram_btn)
        self.Encryption_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Encryption_btn.sizePolicy().hasHeightForWidth())
        self.Encryption_btn.setSizePolicy(sizePolicy)
        self.Encryption_btn.setMinimumSize(QtCore.QSize(120, 50))
        self.Encryption_btn.setMaximumSize(QtCore.QSize(150, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Encryption_btn.setFont(font)
        self.Encryption_btn.setStyleSheet("background-color: rgb(52, 52, 52);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(157, 123, 71);\n"
"\n"
"border: 3px solid rgb(0, 85, 255);\n"
"\n"
"border: 3px solid rgb(178, 0, 242);\n"
"\n"
"border-right: 0px;\n"
"border-top: 0px;")
        self.Encryption_btn.setObjectName("Encryption_btn")
        self.horizontalLayout.addWidget(self.Encryption_btn)
        self.Decryption_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Decryption_btn.sizePolicy().hasHeightForWidth())
        self.Decryption_btn.setSizePolicy(sizePolicy)
        self.Decryption_btn.setMinimumSize(QtCore.QSize(120, 50))
        self.Decryption_btn.setMaximumSize(QtCore.QSize(150, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Decryption_btn.setFont(font)
        self.Decryption_btn.setStyleSheet("background-color: rgb(52, 52, 52);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(157, 123, 71);\n"
"\n"
"border: 3px solid rgb(0, 85, 255);\n"
"\n"
"border: 3px solid rgb(178, 0, 242);\n"
"\n"
"border-right: 0px;\n"
"border-top: 0px;")
        self.Decryption_btn.setObjectName("Decryption_btn")
        self.horizontalLayout.addWidget(self.Decryption_btn)
        self.Break_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Break_btn.sizePolicy().hasHeightForWidth())
        self.Break_btn.setSizePolicy(sizePolicy)
        self.Break_btn.setMinimumSize(QtCore.QSize(120, 50))
        self.Break_btn.setMaximumSize(QtCore.QSize(150, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Break_btn.setFont(font)
        self.Break_btn.setStyleSheet("background-color: rgb(52, 52, 52);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(157, 123, 71);\n"
"\n"
"border: 3px solid rgb(0, 85, 255);\n"
"\n"
"border: 3px solid rgb(178, 0, 242);\n"
"\n"
"border-top: 0px;")
        self.Break_btn.setObjectName("Break_btn")
        self.horizontalLayout.addWidget(self.Break_btn)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget.setStyleSheet("background-color: rgb(62, 62, 62);\n"
"border-bottom: 3px solid rgb(157, 123, 71);\n"
"\n"
"border-bottom: 3px solid rgb(0, 85, 255);\n"
"\n"
"border-bottom: 3px solid rgb(178, 0, 242);")
        self.widget.setObjectName("widget")
        self.horizontalLayout.addWidget(self.widget)
        self.Help_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Help_btn.sizePolicy().hasHeightForWidth())
        self.Help_btn.setSizePolicy(sizePolicy)
        self.Help_btn.setMinimumSize(QtCore.QSize(120, 50))
        self.Help_btn.setMaximumSize(QtCore.QSize(120, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Help_btn.setFont(font)
        self.Help_btn.setStyleSheet("background-color: rgb(52, 52, 52);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(157, 123, 71);\n"
"\n"
"border: 3px solid rgb(0, 85, 255);\n"
"\n"
"border: 3px solid rgb(178, 0, 242);\n"
"\n"
"border-top: 0px;\n"
"")
        self.Help_btn.setObjectName("Help_btn")
        self.horizontalLayout.addWidget(self.Help_btn)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.Layout2 = QtWidgets.QHBoxLayout()
        self.Layout2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.Layout2.setContentsMargins(10, -1, 10, -1)
        self.Layout2.setSpacing(10)
        self.Layout2.setObjectName("Layout2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMinimumSize(QtCore.QSize(600, 400))
        self.textEdit.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-color: rgb(157, 123, 71);\n"
"border-width: 3px;\n"
"border-style: solid;\n"
"\n"
"border: 3px solid rgb(0, 85, 255);\n"
"\n"
"border: 3px solid rgb(178, 0, 242);\n"
"\n"
"background-color: rgb(232, 230, 255);")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_2.addWidget(self.textEdit)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(0, -1, -1, 10)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.FontSize_Header_lab = QtWidgets.QLabel(self.centralwidget)
        self.FontSize_Header_lab.setMinimumSize(QtCore.QSize(120, 30))
        self.FontSize_Header_lab.setMaximumSize(QtCore.QSize(130, 16777215))
        self.FontSize_Header_lab.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(62, 62, 62);\n"
"border: 3px solid rgb(178, 0, 242);\n"
"border-top: 0px;\n"
"\n"
"background-color: rgb(76, 76, 76);")
        self.FontSize_Header_lab.setObjectName("FontSize_Header_lab")
        self.horizontalLayout_7.addWidget(self.FontSize_Header_lab)
        self.FontSize_Value_sBox = QtWidgets.QSpinBox(self.centralwidget)
        self.FontSize_Value_sBox.setMinimumSize(QtCore.QSize(80, 30))
        self.FontSize_Value_sBox.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setKerning(True)
        self.FontSize_Value_sBox.setFont(font)
        self.FontSize_Value_sBox.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(62, 62, 62);\n"
"\n"
"border: 3px solid rgb(178, 0, 242);\n"
"border-top: 0px;\n"
"border-left: 0px;\n"
"border-right:0px;\n"
"background-color: rgb(76, 72, 102);")
        self.FontSize_Value_sBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.FontSize_Value_sBox.setMinimum(6)
        self.FontSize_Value_sBox.setMaximum(20)
        self.FontSize_Value_sBox.setProperty("value", 8)
        self.FontSize_Value_sBox.setObjectName("FontSize_Value_sBox")
        self.horizontalLayout_7.addWidget(self.FontSize_Value_sBox)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 30))
        self.frame.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(62, 62, 62);\n"
"border: 3px solid rgb(178, 0, 242);\n"
"border-top: 0px;\n"
"border-right: 0px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_7.addWidget(self.frame)
        self.GetFromFile_btn = QtWidgets.QPushButton(self.centralwidget)
        self.GetFromFile_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.GetFromFile_btn.setMaximumSize(QtCore.QSize(130, 16777215))
        self.GetFromFile_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(62, 62, 62);\n"
"\n"
"border: 3px solid rgb(178, 0, 242);\n"
"border-top: 0px;\n"
"border-right: 0px;\n"
"\n"
"background-color: rgb(52, 52, 52);")
        self.GetFromFile_btn.setObjectName("GetFromFile_btn")
        self.horizontalLayout_7.addWidget(self.GetFromFile_btn)
        self.SetInFile_btn = QtWidgets.QPushButton(self.centralwidget)
        self.SetInFile_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.SetInFile_btn.setMaximumSize(QtCore.QSize(130, 16777215))
        self.SetInFile_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(62, 62, 62);\n"
"\n"
"border: 3px solid rgb(178, 0, 242);\n"
"border-top: 0px;\n"
"\n"
"background-color: rgb(52, 52, 52);")
        self.SetInFile_btn.setObjectName("SetInFile_btn")
        self.horizontalLayout_7.addWidget(self.SetInFile_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Choose_img_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Choose_img_btn.sizePolicy().hasHeightForWidth())
        self.Choose_img_btn.setSizePolicy(sizePolicy)
        self.Choose_img_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.Choose_img_btn.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Choose_img_btn.setFont(font)
        self.Choose_img_btn.setStyleSheet("border: 3px solid rgb(157, 123, 71);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(62, 62, 62);\n"
"\n"
"border: 3px solid rgb(0, 85, 255);\n"
"\n"
"border: 3px solid rgb(178, 0, 242);\n"
"\n"
"background-color: rgb(52, 52, 52);")
        self.Choose_img_btn.setObjectName("Choose_img_btn")
        self.horizontalLayout_6.addWidget(self.Choose_img_btn)
        self.Img_adres_lab = QtWidgets.QLabel(self.centralwidget)
        self.Img_adres_lab.setMinimumSize(QtCore.QSize(0, 30))
        self.Img_adres_lab.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Img_adres_lab.setStyleSheet("border: 3px solid rgb(157, 123, 71);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(62, 62, 62);\n"
"\n"
"border: 3px solid rgb(0, 85, 255);\n"
"\n"
"border: 3px solid rgb(178, 0, 242);\n"
"border-left: 0px;\n"
"border-right: 0px;\n"
"\n"
"background-color: rgb(62, 62, 62);")
        self.Img_adres_lab.setObjectName("Img_adres_lab")
        self.horizontalLayout_6.addWidget(self.Img_adres_lab)
        self.Encription_to_file_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Encription_to_file_btn.sizePolicy().hasHeightForWidth())
        self.Encription_to_file_btn.setSizePolicy(sizePolicy)
        self.Encription_to_file_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.Encription_to_file_btn.setMaximumSize(QtCore.QSize(100, 30))
        self.Encription_to_file_btn.setStyleSheet("border: 3px solid rgb(157, 123, 71);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(62, 62, 62);\n"
"\n"
"border: 3px solid rgb(0, 85, 255);\n"
"\n"
"border: 3px solid rgb(178, 0, 242);\n"
"\n"
"background-color: rgb(52, 52, 52);")
        self.Encription_to_file_btn.setObjectName("Encription_to_file_btn")
        self.horizontalLayout_6.addWidget(self.Encription_to_file_btn)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButton.setStyleSheet("border: 3px solid rgb(157, 123, 71);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(62, 62, 62);\n"
"\n"
"border: 3px solid rgb(0, 85, 255);\n"
"\n"
"border: 3px solid rgb(178, 0, 242);\n"
"\n"
"background-color: rgb(52, 52, 52);\n"
"border-left: 0px;")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.Layout2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Status_header_lab = QtWidgets.QLabel(self.centralwidget)
        self.Status_header_lab.setMinimumSize(QtCore.QSize(190, 30))
        self.Status_header_lab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Status_header_lab.setStyleSheet("background-color: rgb(76, 76, 76);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(157, 123, 71);\n"
"\n"
"border: 3px solid rgb(0, 85, 255);\n"
"\n"
"border: 3px solid rgb(178, 0, 242);")
        self.Status_header_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.Status_header_lab.setObjectName("Status_header_lab")
        self.verticalLayout.addWidget(self.Status_header_lab)
        self.Status_lab = QtWidgets.QLabel(self.centralwidget)
        self.Status_lab.setMinimumSize(QtCore.QSize(190, 70))
        self.Status_lab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Status_lab.setStyleSheet("background-color: rgb(52, 52, 52);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(157, 123, 71);\n"
"\n"
"border: 3px solid rgb(0, 85, 255);\n"
"\n"
"border: 3px solid rgb(178, 0, 242);\n"
"\n"
"border-top: 0px;\n"
"border-bottom: 0px;\n"
"\n"
"background-color: rgb(62, 62, 62);")
        self.Status_lab.setWordWrap(True)
        self.Status_lab.setObjectName("Status_lab")
        self.verticalLayout.addWidget(self.Status_lab)
        self.Method_header_lab = QtWidgets.QLabel(self.centralwidget)
        self.Method_header_lab.setMinimumSize(QtCore.QSize(190, 30))
        self.Method_header_lab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Method_header_lab.setStyleSheet("background-color: rgb(76, 76, 76);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(157, 123, 71);\n"
"\n"
"border: 3px solid rgb(0, 85, 255);\n"
"\n"
"border: 3px solid rgb(178, 0, 242);")
        self.Method_header_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.Method_header_lab.setObjectName("Method_header_lab")
        self.verticalLayout.addWidget(self.Method_header_lab)
        self.Method_cBox = QtWidgets.QComboBox(self.centralwidget)
        self.Method_cBox.setMinimumSize(QtCore.QSize(190, 30))
        self.Method_cBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Method_cBox.setStyleSheet("background-color: rgb(52, 52, 52);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(157, 123, 71);\n"
"\n"
"border: 3px solid rgb(0, 85, 255);\n"
"\n"
"border: 3px solid rgb(178, 0, 242);\n"
"\n"
"border-top: 0px;\n"
"border-bottom: 0px;\n"
"background-color: rgb(76, 72, 102);")
        self.Method_cBox.setObjectName("Method_cBox")
        self.Method_cBox.addItem("")
        self.Method_cBox.addItem("")
        self.Method_cBox.addItem("")
        self.Method_cBox.addItem("")
        self.verticalLayout.addWidget(self.Method_cBox)
        self.Breaking_settings_header_lab = QtWidgets.QLabel(self.centralwidget)
        self.Breaking_settings_header_lab.setMinimumSize(QtCore.QSize(0, 30))
        self.Breaking_settings_header_lab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Breaking_settings_header_lab.setStyleSheet("background-color: rgb(76, 76, 76);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(157, 123, 71);\n"
"\n"
"border: 3px solid rgb(0, 85, 255);\n"
"\n"
"border: 3px solid rgb(178, 0, 242);")
        self.Breaking_settings_header_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.Breaking_settings_header_lab.setObjectName("Breaking_settings_header_lab")
        self.verticalLayout.addWidget(self.Breaking_settings_header_lab)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Key_power_header_lab = QtWidgets.QLabel(self.centralwidget)
        self.Key_power_header_lab.setMinimumSize(QtCore.QSize(85, 30))
        self.Key_power_header_lab.setMaximumSize(QtCore.QSize(85, 30))
        self.Key_power_header_lab.setStyleSheet("background-color: rgb(76, 76, 76);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(157, 123, 71);\n"
"\n"
"border: 3px solid rgb(0, 85, 255);\n"
"\n"
"border: 3px solid rgb(178, 0, 242);\n"
"\n"
"border-top: 0px;\n"
"border-bottom: 0px;")
        self.Key_power_header_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.Key_power_header_lab.setObjectName("Key_power_header_lab")
        self.horizontalLayout_2.addWidget(self.Key_power_header_lab)
        self.Key_power_sBox = QtWidgets.QSpinBox(self.centralwidget)
        self.Key_power_sBox.setMinimumSize(QtCore.QSize(105, 30))
        self.Key_power_sBox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Key_power_sBox.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-right: 3px solid rgb(157, 123, 71);\n"
"\n"
"border-right: 3px solid rgb(0, 85, 255);\n"
"\n"
"border: 3px solid rgb(178, 0, 242);\n"
"border-bottom: 0px;\n"
"border-top: 0px;\n"
"border-left: 0px;\n"
"\n"
"\n"
"background-color: rgb(76, 72, 102);")
        self.Key_power_sBox.setObjectName("Key_power_sBox")
        self.horizontalLayout_2.addWidget(self.Key_power_sBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Search_word_header_lab = QtWidgets.QLabel(self.centralwidget)
        self.Search_word_header_lab.setMinimumSize(QtCore.QSize(60, 32))
        self.Search_word_header_lab.setMaximumSize(QtCore.QSize(60, 32))
        self.Search_word_header_lab.setStyleSheet("background-color: rgb(76, 76, 76);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(157, 123, 71);\n"
"\n"
"border: 3px solid rgb(0, 85, 255);\n"
"\n"
"border: 3px solid rgb(178, 0, 242);")
        self.Search_word_header_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.Search_word_header_lab.setObjectName("Search_word_header_lab")
        self.horizontalLayout_3.addWidget(self.Search_word_header_lab)
        self.Search_word_lEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Search_word_lEdit.setMinimumSize(QtCore.QSize(130, 32))
        self.Search_word_lEdit.setMaximumSize(QtCore.QSize(16777215, 32))
        self.Search_word_lEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(157, 123, 71);\n"
"\n"
"border: 3px solid rgb(0, 85, 255);\n"
"\n"
"border: 3px solid rgb(178, 0, 242);\n"
"\n"
"border-left: 0px;")
        self.Search_word_lEdit.setObjectName("Search_word_lEdit")
        self.horizontalLayout_3.addWidget(self.Search_word_lEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.KeyBlock_header_lab = QtWidgets.QLabel(self.centralwidget)
        self.KeyBlock_header_lab.setMinimumSize(QtCore.QSize(190, 24))
        self.KeyBlock_header_lab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.KeyBlock_header_lab.setStyleSheet("background-color: rgb(76, 76, 76);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(157, 123, 71);\n"
"\n"
"border: 3px solid rgb(0, 85, 255);\n"
"\n"
"border: 3px solid rgb(178, 0, 242);\n"
"\n"
"border-top: 0px;\n"
"border-bottom: 0px;")
        self.KeyBlock_header_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.KeyBlock_header_lab.setObjectName("KeyBlock_header_lab")
        self.verticalLayout.addWidget(self.KeyBlock_header_lab)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Key_now_header_lab = QtWidgets.QLabel(self.centralwidget)
        self.Key_now_header_lab.setMinimumSize(QtCore.QSize(70, 30))
        self.Key_now_header_lab.setMaximumSize(QtCore.QSize(70, 30))
        self.Key_now_header_lab.setStyleSheet("background-color: rgb(76, 76, 76);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(157, 123, 71);\n"
"\n"
"border: 3px solid rgb(0, 85, 255);\n"
"\n"
"border: 3px solid rgb(178, 0, 242);\n"
"\n"
"border-bottom: 0px;")
        self.Key_now_header_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.Key_now_header_lab.setObjectName("Key_now_header_lab")
        self.horizontalLayout_4.addWidget(self.Key_now_header_lab)
        self.Key_now_lEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Key_now_lEdit.setMinimumSize(QtCore.QSize(70, 30))
        self.Key_now_lEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Key_now_lEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-top: 3px solid rgb(157, 123, 71);\n"
"\n"
"border-top: 3px solid rgb(0, 85, 255);\n"
"\n"
"border-top: 3px solid rgb(178, 0, 242);")
        self.Key_now_lEdit.setObjectName("Key_now_lEdit")
        self.horizontalLayout_4.addWidget(self.Key_now_lEdit)
        self.Add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Add_btn.setMinimumSize(QtCore.QSize(50, 30))
        self.Add_btn.setMaximumSize(QtCore.QSize(50, 30))
        self.Add_btn.setStyleSheet("border: 3px solid rgb(157, 123, 71);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border: 3px solid rgb(0, 85, 255);\n"
"\n"
"border: 3px solid rgb(178, 0, 242);\n"
"\n"
"border-bottom: 0px;\n"
"\n"
"background-color: rgb(52, 52, 52);")
        self.Add_btn.setObjectName("Add_btn")
        self.horizontalLayout_4.addWidget(self.Add_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.Keys_header_lab = QtWidgets.QLabel(self.centralwidget)
        self.Keys_header_lab.setMinimumSize(QtCore.QSize(190, 30))
        self.Keys_header_lab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Keys_header_lab.setStyleSheet("background-color: rgb(76, 76, 76);\n"
"color: rgb(255, 255, 255);\n"
"border: 3px solid rgb(157, 123, 71);\n"
"\n"
"border: 3px solid rgb(0, 85, 255);\n"
"\n"
"border: 3px solid rgb(178, 0, 242);")
        self.Keys_header_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.Keys_header_lab.setObjectName("Keys_header_lab")
        self.verticalLayout.addWidget(self.Keys_header_lab)
        self.Keys_lWidget = QtWidgets.QListWidget(self.centralwidget)
        self.Keys_lWidget.setMinimumSize(QtCore.QSize(190, 0))
        self.Keys_lWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Keys_lWidget.setStyleSheet("background-color: rgb(52, 52, 52);\n"
"border-left: 3px solid rgb(157, 123, 71);\n"
"border-right: 3px solid rgb(157, 123, 71);\n"
"\n"
"border: 3px solid rgb(0, 85, 255);\n"
"border: 3px solid rgb(178, 0, 242);\n"
"border-top: 0px;\n"
"border-bottom: 0px;\n"
"\n"
"color: rgb(255, 255, 255);\n"
"\n"
"background-color: rgb(62, 62, 62);")
        self.Keys_lWidget.setObjectName("Keys_lWidget")
        self.verticalLayout.addWidget(self.Keys_lWidget)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Take_btn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.Take_btn.sizePolicy().hasHeightForWidth())
        self.Take_btn.setSizePolicy(sizePolicy)
        self.Take_btn.setMinimumSize(QtCore.QSize(95, 30))
        self.Take_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Take_btn.setStyleSheet("border: 3px solid rgb(157, 123, 71);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(62, 62, 62);\n"
"\n"
"border: 3px solid rgb(0, 85, 255);\n"
"\n"
"border: 3px solid rgb(178, 0, 242);\n"
"\n"
"border-right: 0px;\n"
"\n"
"background-color: rgb(52, 52, 52);")
        self.Take_btn.setObjectName("Take_btn")
        self.horizontalLayout_5.addWidget(self.Take_btn)
        self.Del_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Del_btn.setMinimumSize(QtCore.QSize(95, 30))
        self.Del_btn.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Del_btn.setStyleSheet("border: 3px solid rgb(157, 123, 71);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(62, 62, 62);\n"
"\n"
"border: 3px solid rgb(0, 85, 255);\n"
"\n"
"border: 3px solid rgb(178, 0, 242);\n"
"\n"
"background-color: rgb(52, 52, 52);")
        self.Del_btn.setObjectName("Del_btn")
        self.horizontalLayout_5.addWidget(self.Del_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.Layout2.addLayout(self.verticalLayout)
        self.Layout2.setStretch(0, 1)
        self.gridLayout.addLayout(self.Layout2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Violet"))
        self.Save_btn.setText(_translate("MainWindow", "Сохранить"))
        self.Bd_btn.setText(_translate("MainWindow", "База данных"))
        self.Histogram_btn.setText(_translate("MainWindow", "Гистограма"))
        self.Encryption_btn.setText(_translate("MainWindow", "Шифровка"))
        self.Decryption_btn.setText(_translate("MainWindow", "Расшифровка"))
        self.Break_btn.setText(_translate("MainWindow", "Взлом"))
        self.Help_btn.setText(_translate("MainWindow", "Помощь"))
        self.FontSize_Header_lab.setText(_translate("MainWindow", "Размер шрифта:"))
        self.GetFromFile_btn.setText(_translate("MainWindow", "Загрузить"))
        self.SetInFile_btn.setText(_translate("MainWindow", "Выгрузить"))
        self.Choose_img_btn.setText(_translate("MainWindow", "Выбрать изображение:"))
        self.Img_adres_lab.setText(_translate("MainWindow", "Адрес изображения"))
        self.Encription_to_file_btn.setText(_translate("MainWindow", "Зашифровать"))
        self.pushButton.setText(_translate("MainWindow", "Расшифровать"))
        self.Status_header_lab.setText(_translate("MainWindow", "Статус:"))
        self.Status_lab.setText(_translate("MainWindow", " ..."))
        self.Method_header_lab.setText(_translate("MainWindow", "Метод"))
        self.Method_cBox.setItemText(0, _translate("MainWindow", "Одноалфавитный метод"))
        self.Method_cBox.setItemText(1, _translate("MainWindow", "Перестановка символов"))
        self.Method_cBox.setItemText(2, _translate("MainWindow", "Инверсный метод"))
        self.Method_cBox.setItemText(3, _translate("MainWindow", "Гаммирование"))
        self.Breaking_settings_header_lab.setText(_translate("MainWindow", "Настройки взлома"))
        self.Key_power_header_lab.setText(_translate("MainWindow", "Сила ключа"))
        self.Search_word_header_lab.setText(_translate("MainWindow", "Слово"))
        self.KeyBlock_header_lab.setText(_translate("MainWindow", "Менеджер ключей:"))
        self.Key_now_header_lab.setText(_translate("MainWindow", "Ключ"))
        self.Add_btn.setText(_translate("MainWindow", "\\/"))
        self.Keys_header_lab.setText(_translate("MainWindow", "Ключи:"))
        self.Take_btn.setText(_translate("MainWindow", "Взять"))
        self.Del_btn.setText(_translate("MainWindow", "Удалить"))
